### ISSUE TITLE
Option to mangle / overwrite filenames / directory names

### ISSUE THREAD

**Issue by DanielRuf** [DanielRuf/secure-shred#10]
It might be good to add another level of entropy by changing filenames to prevent as many leftover details as possible.

Also shorten the size of files / dirs.

**Comment by peter279k** [comment]
I think it should more explanation about how to implement this feature to have the option for overwriting/mangling file and directory names.

**Comment by dulldusk** [comment]
Nice idea! rename the file to some random name before delete.

**Comment by DanielRuf** [comment]
Implemented in https://github.com/DanielRuf/secure-shred/tree/feature/mangle-filename

Would be cool if you could test this and give some feedback.
