### ISSUE TITLE
Use .editorconfig for consistent code style

### ISSUE THREAD

**Issue by githubuserx** [DanielRuf/secure-shred#11]
Currently there are different identation settings used for different files.
I suggest using a common PHP code style like e.g. `PSR-1/PSR-2` or similar to make it consistent.

**Comment by DanielRuf** [comment]
Good suggestion.

Basically the difference is because we use two spaces at work in general in all projects and I've started the testsuite from an example snippet by Sebastian.

I'm generally not a big fan of 4 spaces currently. So what do you think, which editorconfig rules and settings do you suggest?

**Comment by githubuserx** [comment]
I'm more used to 4 spaces, but it's fine either way. I just want to be able to use features like "auto indent" etc. without messing up all whitespace.

I'd use something like this for now
```
[*]
charset = utf-8
end_of_line = crlf
insert_final_newline = false
indent_style = space
indent_size = 4

[{composer.lock, *.json}]
indent_size = 2

[{*.yml, *.yaml}]
indent_size = 2
```

**Comment by DanielRuf** [comment]
Generally it makes not much sense to change the composer related files as these are automatically created with 4 spaces (or did I miss something?).

I'll check the needed settings and provide a PR in the next days with a first dditorconfig file.

**Comment by githubuserx** [comment]
That's just a preset from IntelliJ. Makes sense to not change generated files.

**Comment by DanielRuf** [comment]
I've added a basic editorconfig file.
You can see the changes at https://github.com/DanielRuf/secure-shred/commit/4235c5c671a3fdc8591baa572d0f03a89c8369ab

**Comment by DanielRuf** [comment]
Closing as a first config file is used now and PHP CS Fixer also checks the indentation.
If further changes are needed a PR is very welcome.
