### ISSUE TITLE
PHP ^5.3 seems to be supported, but ^7.1 is required in Composer?

### ISSUE THREAD

**Issue by meitar** [DanielRuf/secure-shred#4]
According to the project's `composer.json` file, PHP 7.1 or greater is required, but I can't seem to find anything in the `src/Shred.php` file that actually requires this. I have also tested this library using PHP 5.5.9 and, save for the call to `random_bytes()`, it will still work.

Thus, my question: if I polyfill the calls to the `random_*()` functions (for example, with the [`paragonie/random_compat`](https://github.com/paragonie/random_compat) library), is there any immediate danger in using this library while running older PHP versions?

Even more specifically: I am interested in utilizing this library for a WordPress plugin. WordPress ships the above-mentioned `random_compat` library. Therefore, it seems I can use this in my project, as long as PHP 5.3 or greater is used. Is this correct?

**Comment by DanielRuf** [comment]
Hi @meitar, nice to see you again.

> Thus, my question: if I polyfill the calls to the random_*() functions (for example, with the paragonie/random_compat library), is there any immediate danger in using this library while running older PHP versions?

I see no problems if these functions are polyfilled. I'll expand the test matrix for PHP 5.*.

Generally I've set the minimum tested and required PHP version to the active PHP versions (7.0 and older already reached their EOL) and the used PHPUnit version only supports these.

I will check if I can expand the test matrix and adjust the devdependencies and the testsuite to support older major PHPUnit releases.

**Comment by DanielRuf** [comment]
> Therefore, it seems I can use this in my project, as long as PHP 5.3 or greater is used. Is this correct?

Correct.

**Comment by meitar** [comment]
Thanks for getting back to me so quick. :) As WordPress still supports PHP 5.2+ (despite recommending 7.1+), and so many shared hosting providers still run sites on PHP 5.x, I would like to ensure that my plugin still works for them if I include this small library. :)

**Comment by meitar** [comment]
Ah, my bad, your use of PHP namespaces means the minimum required PHP version is actually PHP 5.4, not 5.3.

**Comment by meitar** [comment]
> Which PHP 5 versions do you want to see tested?

I would like to support at least PHP 5.4 and later. :) Thank you!

**Comment by DanielRuf** [comment]
Ok, I'll add 5.4 and 5.5 later.

7.0 is not tested, is this ok or shall I expand the whole test matrix?

**Comment by meitar** [comment]
I don't have strong feelings about PHP 7.0. :) Thanks for the 5.x additions.

**Comment by DanielRuf** [comment]
PHP 5.4 and PHP 5.5 were added now.

https://github.com/DanielRuf/secure-shred/commit/26cb93c13fd087bcbcbe3ddd929fccf527fc51ce
https://travis-ci.org/DanielRuf/secure-shred/builds/473062598

Let me know if this is sufficient and I'll close this issue.

**Comment by meitar** [comment]
Yup, this is great. :) Thanks!
